refactor: rework the ```DOCUMENTATION``` file into the ```README.md``` file inside the ```setup``` directory
YangCatalog/deployment pull request #168
Opened 2022-11-07 12:52 UTC by Fagtoy

Removed the ```DOCUMENTATION``` file and created the ```README.md``` file inside the ```setup``` directory

resolves #167

2022-11-07 13:34 UTC, SlavomirMazurPantheon requested changes

2022-11-07 13:34 UTC, SlavomirMazurPantheon commented on setup/README.md
> +   - **Optional**: copy ```/var/yang``` into ```<YANG_RESOURCES>``` (change ```<YANG_ID>``` and ```<YANG_GID>``` in the ```.env``` file to user ID and GID you are using in host)
We can remove this point `**Optional**: copy /var/yang ...`

2022-11-07 13:34 UTC, SlavomirMazurPantheon commented on setup/README.md
> +8. Set ```max_map_count``` kernel setting using ```$ sysctl -w vm.max_map_count=262144``` because elasticsearch will fail otherwise.
capital `E` in `Elasticsearch`

2022-11-07 13:34 UTC, SlavomirMazurPantheon commented on setup/README.md
> +5. If you want to clean either elasticsearch data, remove everything from ```<ELASTICSEARCH_DATA>``` and ```<ELASTICSEARCH_LOG>``` folders
capital `E` in `Elasticsearch`

2022-11-08 06:36 UTC, SlavomirMazurPantheon approved these changes

2022-11-08 08:11 UTC, richardzilincikPantheon approved these changes

2022-11-08 08:35 UTC, merged